#!/bin/bash

# Usage: search <search_term> [search_directory]
#        search --help

#-------------------------------------------
# Show help if requested or upon input error
#-------------------------------------------
show_usage() {
   echo "Usage: search <search_term> [search_directory]"
   echo "       search --help"
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
   show_usage
   exit
fi

for arg in $@; do
   if [ "$arg" == "--help" ]; then
      show_usage
      exit
   fi
done

#---------------------------------
# Setup variables to pass to egrep
#---------------------------------
SEARCH_TERM=$1
# May wish to override DEFAULT_SEARCH_DIRECTORIES with a specific directory
# list as applicable to the project you are currently working on.
# In liu of another default, search in the current working directory "."
DEFAULT_SEARCH_DIRECTORIES=.
if [[ $# -lt 2 ]]; then
   SEARCH_DIRECTORIES=$DEFAULT_SEARCH_DIRECTORIES
else
   SEARCH_DIRECTORIES=$2
fi

#---------------
# Perform search
#---------------
egrep -ir --include={"*.f","*.f90","*.F","*.F90","*.h","*.c","*.cpp","*.tcc","*.py","*.m"} --color=always $SEARCH_TERM $SEARCH_DIRECTORIES
